# -*- mode: ruby -*-
# vi: set ft=ruby :

N=3

Vagrant.configure("2") do |config|

  (1..N).each do |i|
    config.vm.define "minio-node-#{i}" do |node|
      node.vm.hostname = "minio-node-#{i}"
      node.vm.box = "ubuntu/xenial64"
      node.vm.network "private_network", ip: "192.168.1.10#{i}"
      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "512"
      end
      if i == N
        node.vm.provision :ansible do |ansible|
          ansible.limit = "all"
          ansible.playbook = "playbook.yml"
        end
      end
    end
  end
end
